apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-apache
  labels:
    app: swe645-hw3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe645-hw3
  template:
    metadata:
      labels:
        app: swe645-hw3
    spec:
      containers:
        - name: swe645-hw3-container
          image: banudeep/hw3:{{IMAGE_TAG}}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
