apiVersion: v1
kind: Service
metadata:
  name: my-service-apache
  labels: 
    app: swe645-hw2 
spec:
  selector:
    app: swe645-hw2
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    name: http
  - port: 443
    protocol: TCP
    name: https